(function(){
const EVENT_LABELS={member_card_click:'人物點擊',contact_click:'聯絡方式點擊',chat_member_open:'小幫手推薦人物',chat_open:'開啟小幫手',chat_message:'使用者詢問',chat_intent:'選擇功能',chat_problem_pick:'選擇需求',need_select:'前台類別點擊',chat_fallback:'無法判斷'};
let rawLogsOpen=false;
function loadCss(){if(document.querySelector('link[href="./analytics.css"]'))return;const l=document.createElement('link');l.rel='stylesheet';l.href='./analytics.css';document.head.appendChild(l)}
function installUi(){
 loadCss();
 const memberList=document.getElementById('memberList');
 if(memberList&&!document.getElementById('memberSearch')){const wrap=document.createElement('div');wrap.className='member-search-wrap';wrap.innerHTML='<input id="memberSearch" class="member-search" placeholder="搜尋姓名、公司、專業、編號…"><div id="memberSearchCount" class="search-count"></div>';memberList.parentElement.insertBefore(wrap,memberList);document.getElementById('memberSearch').addEventListener('input',()=>renderMemberList())}
 const dashboard=document.getElementById('page-dashboard');
 if(dashboard&&!document.getElementById('dashboardAnalytics')){const box=document.createElement('div');box.id='dashboardAnalytics';box.innerHTML='<div id="dashboardInsights" class="insight-grid"></div><div class="analysis-grid"><div class="analysis-card"><h3>近 7 日互動趨勢</h3><div class="sub">看前台的查看、聯絡與需求選擇是否持續增加。</div><div id="dashboardTrend"></div></div><div class="analysis-card"><h3>熱門需求類別</h3><div class="sub">使用者最常點擊哪些工程需求。</div><div id="needBars"></div></div></div><div class="analysis-card"><h3>人物轉換排行</h3><div class="sub">從「查看人物」到「點擊聯絡方式」的轉換。資料量少時先看趨勢，不建議過度解讀。</div><div id="conversionTable"></div></div>';const stats=dashboard.querySelector('.stats');stats?.insertAdjacentElement('afterend',box)}
 const logs=document.getElementById('page-logs');
 if(logs&&!document.getElementById('logAnalysis')){const panel=logs.querySelector('.panel');const box=document.createElement('div');box.id='logAnalysis';box.innerHTML='<div id="logSummary" class="log-summary"></div><div class="analysis-grid"><div class="analysis-card"><h3>互動類型分布</h3><div class="sub">使用者主要是在看人物、找聯絡方式，還是使用小幫手。</div><div id="logTypeBars"></div></div><div class="analysis-card"><h3>熱門人物</h3><div class="sub">依人物查看與聯絡行為合計。</div><div id="logMemberBars"></div></div></div><div class="raw-log-toggle"><button id="toggleRawLogs">顯示原始紀錄</button></div>';panel?.parentElement.insertBefore(box,panel);if(panel)panel.classList.add('raw-log-collapsed');document.getElementById('toggleRawLogs').onclick=()=>{rawLogsOpen=!rawLogsOpen;panel?.classList.toggle('raw-log-collapsed',!rawLogsOpen);document.getElementById('toggleRawLogs').textContent=rawLogsOpen?'隱藏原始紀錄':'顯示原始紀錄'}}
}
function dayKey(d){return new Intl.DateTimeFormat('zh-TW',{timeZone:'Asia/Taipei',month:'2-digit',day:'2-digit'}).format(d)}
function makeDays(n){const a=[];for(let i=n-1;i>=0;i--){const d=new Date(Date.now()-i*86400000);a.push({key:dayKey(d),date:d})}return a}
function barChart(el,data){if(!el)return;const max=Math.max(1,...data.map(x=>x.value));el.innerHTML=data.length?`<div class="bar-chart">${data.map(x=>`<div class="bar-row" title="${esc(x.label)}：${x.value}"><div class="bar-label">${esc(x.label)}</div><div class="bar-track"><div class="bar-fill" style="width:${Math.max(2,x.value/max*100)}%"></div></div><div class="bar-value">${x.value}</div></div>`).join('')}</div>`:'<div class="empty">目前還沒有足夠資料。</div>'}
function lineChart(el,days,series){if(!el)return;const all=series.flatMap(s=>s.values);const max=Math.max(1,...all),w=640,h=190,padL=30,padR=16,padT=12,padB=32;const x=i=>padL+(w-padL-padR)*(days.length===1?0:i/(days.length-1));const y=v=>padT+(h-padT-padB)*(1-v/max);const grid=[0,.25,.5,.75,1].map(t=>`<line class="trend-grid" x1="${padL}" y1="${padT+(h-padT-padB)*t}" x2="${w-padR}" y2="${padT+(h-padT-padB)*t}"/>`).join('');const labels=days.map((d,i)=>`<text class="trend-label" x="${x(i)}" y="${h-8}" text-anchor="middle">${d.key}</text>`).join('');const lines=series.map((s,si)=>{const pts=s.values.map((v,i)=>`${x(i)},${y(v)}`).join(' ');const dots=s.values.map((v,i)=>`<circle class="trend-dot-${['a','b','c'][si]}" cx="${x(i)}" cy="${y(v)}" r="3"/>`).join('');return `<polyline class="trend-line-${['a','b','c'][si]}" points="${pts}"/>${dots}`}).join('');el.innerHTML=`<div class="trend-wrap"><svg class="trend-svg" viewBox="0 0 ${w} ${h}" role="img">${grid}${lines}${labels}</svg></div><div class="legend">${series.map((s,i)=>`<span><i class="${['a','b','c'][i]}"></i>${esc(s.label)}</span>`).join('')}</div>`}
function insightCards(ev){const clicks=ev.filter(x=>x.event_type==='member_card_click'||x.event_type==='chat_member_open'),contacts=ev.filter(x=>x.event_type==='contact_click'),needs=ev.filter(x=>x.event_type==='need_select'),fallback=ev.filter(x=>x.event_type==='chat_fallback'),messages=ev.filter(x=>x.event_type==='chat_message');const memberCounts={};clicks.forEach(x=>{if(x.member_name)memberCounts[x.member_name]=(memberCounts[x.member_name]||0)+1});const topMember=Object.entries(memberCounts).sort((a,b)=>b[1]-a[1])[0];const needCounts={};needs.forEach(x=>{const label=x.meta?.title||x.intent||x.meta?.need_key||'其他';needCounts[label]=(needCounts[label]||0)+1});const topNeed=Object.entries(needCounts).sort((a,b)=>b[1]-a[1])[0];const conv=clicks.length?Math.round(contacts.length/clicks.length*100):0;const fallbackRate=messages.length?Math.round(fallback.length/messages.length*100):0;return [{title:'最常被查看',value:topMember?topMember[0]:'尚無資料',sub:topMember?`${topMember[1]} 次人物互動`:'開始累積前台使用數據後會顯示'},{title:'最熱門需求',value:topNeed?topNeed[0]:'尚無資料',sub:topNeed?`${topNeed[1]} 次類別點擊`:'尚未有類別點擊資料'},{title:'聯絡轉換率',value:`${conv}%`,sub:`${contacts.length} 次聯絡 ÷ ${clicks.length} 次人物互動；小樣本僅供趨勢參考`},{title:'小幫手無法判斷率',value:`${fallbackRate}%`,sub:`${fallback.length} 次無法判斷 ÷ ${messages.length} 次詢問`} ]}
const oldLoadDashboard=window.loadDashboard;
window.loadDashboard=async function(){
 const [mr,er]=await Promise.all([sb.from('bni_members').select('id,name,is_published'),sb.from('bni_behavior_events').select('*').order('created_at',{ascending:false}).limit(3000)]);if(mr.error||er.error){notice('儀表板讀取失敗。','error');return}const ms=mr.data||[],ev=er.data||[];events=ev;const clicks=ev.filter(x=>x.event_type==='member_card_click'||x.event_type==='chat_member_open'),contacts=ev.filter(x=>x.event_type==='contact_click'),chat=ev.filter(x=>x.event_type==='chat_open'),seven=Date.now()-7*86400000,recent=ev.filter(x=>new Date(x.created_at).getTime()>=seven);$('statMembers').textContent=ms.filter(x=>x.is_published!==false).length;$('statMemberClicks').textContent=clicks.length;$('statContactClicks').textContent=contacts.length;$('statRecent').textContent=recent.length;$('statChat').textContent=chat.length;
 const by={};ms.forEach(m=>by[m.name]={name:m.name,profile:0,contact:0});clicks.forEach(x=>{if(x.member_name){by[x.member_name]??={name:x.member_name,profile:0,contact:0};by[x.member_name].profile++}});contacts.forEach(x=>{if(x.member_name){by[x.member_name]??={name:x.member_name,profile:0,contact:0};by[x.member_name].contact++}});const top=Object.values(by).sort((a,b)=>(b.profile+b.contact)-(a.profile+a.contact)).slice(0,10);$('topMembers').innerHTML=top.length?top.map(x=>`<div class="top-row"><b>${esc(x.name)}</b><span>人物 ${x.profile}</span><span>聯絡 ${x.contact}</span></div>`).join(''):'<div class="empty">目前還沒有點擊資料。</div>';$('recentEvents').innerHTML=ev.slice(0,8).map(x=>`<div class="log-row"><div class="time">${fmtTime(x.created_at)}</div><div><span class="badge">${EVENT_LABELS[x.event_type]||esc(x.event_type)}</span></div><div>${esc(x.member_name||x.intent||'')}</div><div>${esc(x.query_text||x.meta?.label||x.meta?.title||'')}</div></div>`).join('')||'<div class="empty">尚無紀錄。</div>';
 const ins=insightCards(ev);$('dashboardInsights').innerHTML=ins.map(x=>`<div class="insight"><b>${x.title}</b><strong>${esc(x.value)}</strong><span>${esc(x.sub)}</span></div>`).join('');const days=makeDays(7),counts=(types)=>days.map(d=>ev.filter(x=>dayKey(new Date(x.created_at))===d.key&&types.includes(x.event_type)).length);lineChart($('dashboardTrend'),days,[{label:'人物查看',values:counts(['member_card_click','chat_member_open'])},{label:'聯絡點擊',values:counts(['contact_click'])},{label:'需求選擇',values:counts(['need_select','chat_problem_pick'])}]);const needMap={};ev.filter(x=>x.event_type==='need_select'||x.event_type==='chat_problem_pick').forEach(x=>{const k=x.meta?.title||x.intent||x.meta?.need_key||'其他';needMap[k]=(needMap[k]||0)+1});barChart($('needBars'),Object.entries(needMap).sort((a,b)=>b[1]-a[1]).slice(0,8).map(([label,value])=>({label,value})));
 $('conversionTable').innerHTML=`<div class="conversion-table"><div class="conv-row head"><span>成員</span><span>查看</span><span>聯絡</span><span>轉換率</span></div>${Object.values(by).filter(x=>x.profile||x.contact).sort((a,b)=>b.profile-a.profile).slice(0,12).map(x=>{const r=x.profile?Math.round(x.contact/x.profile*100):0;return `<div class="conv-row"><b>${esc(x.name)}</b><span>${x.profile}</span><span>${x.contact}</span><span class="${r?'rate-good':'rate-zero'}">${r}%</span></div>`}).join('')}</div>`;
};
const oldRenderMemberList=window.renderMemberList;
window.renderMemberList=function(){const el=$('memberList'),q=(document.getElementById('memberSearch')?.value||'').trim().toLowerCase();const filtered=!q?members:members.filter(m=>[m.member_no,m.name,m.company,m.title,m.expertise_category,m.services].filter(Boolean).join(' ').toLowerCase().includes(q));el.innerHTML=filtered.length?filtered.map(m=>`<button class="list-item ${currentMember?.id===m.id?'active':''}" data-member="${m.id}"><b>${m.member_no||'-'}｜${esc(m.name)}</b><span>${esc(m.company||'')}｜${m.is_published===false?'前台隱藏':'前台顯示'}</span></button>`).join(''):'<div class="no-search">找不到符合的成員。</div>';el.querySelectorAll('[data-member]').forEach(b=>b.onclick=()=>selectMember(b.dataset.member));const count=document.getElementById('memberSearchCount');if(count)count.textContent=q?`找到 ${filtered.length} / ${members.length} 位`:`共 ${members.length} 位成員`};
function analyzeLogs(rows){const clicks=rows.filter(x=>x.event_type==='member_card_click'||x.event_type==='chat_member_open'),contacts=rows.filter(x=>x.event_type==='contact_click'),needs=rows.filter(x=>x.event_type==='need_select'||x.event_type==='chat_problem_pick'),messages=rows.filter(x=>x.event_type==='chat_message');const conv=clicks.length?Math.round(contacts.length/clicks.length*100):0;$('logSummary').innerHTML=[['目前紀錄',rows.length],['人物互動',clicks.length],['聯絡點擊',contacts.length],['聯絡轉換率',conv+'%']].map(([a,b])=>`<div class="mini-stat"><span>${a}</span><strong>${b}</strong></div>`).join('');const types={};rows.forEach(x=>types[EVENT_LABELS[x.event_type]||x.event_type]=(types[EVENT_LABELS[x.event_type]||x.event_type]||0)+1);barChart($('logTypeBars'),Object.entries(types).sort((a,b)=>b[1]-a[1]).slice(0,8).map(([label,value])=>({label,value})));const people={};rows.forEach(x=>{if(x.member_name)people[x.member_name]=(people[x.member_name]||0)+1});barChart($('logMemberBars'),Object.entries(people).sort((a,b)=>b[1]-a[1]).slice(0,8).map(([label,value])=>({label,value})))}
const oldLoadLogs=window.loadLogs;
window.loadLogs=async function(){const {data,error}=await sb.from('bni_behavior_events').select('*').order('created_at',{ascending:false}).limit(1000);if(error)return notice('媒合紀錄讀取失敗：'+error.message,'error');events=data||[];renderLogs()};
const oldRenderLogs=window.renderLogs;
window.renderLogs=function(){const filter=$('logFilter').value,rows=filter==='all'?events:events.filter(x=>x.event_type===filter);analyzeLogs(rows);$('logList').innerHTML=rows.length?rows.map(x=>`<div class="log-row"><div class="time">${fmtTime(x.created_at)}</div><div><span class="badge">${EVENT_LABELS[x.event_type]||esc(x.event_type)}</span></div><div>${esc(x.member_name||x.intent||'—')}</div><div>${esc(x.query_text||x.meta?.label||x.meta?.title||x.meta?.need_key||'')}</div></div>`).join(''):'<div class="empty">沒有符合的紀錄。</div>'};
installUi();
if(document.getElementById('memberList'))renderMemberList();
})();