(function(){
let assistantRules=[],assistantReports=[],editingRule=null;
const a=id=>document.getElementById(id);
const splitList=v=>String(v||'').split(/[，,\n]/).map(x=>x.trim()).filter(Boolean);
function install(){
 const nav=document.querySelector('.nav-list');
 if(nav&&!a('assistantAdminNav')){const btn=document.createElement('button');btn.id='assistantAdminNav';btn.className='nav-btn';btn.dataset.page='assistant';btn.innerHTML='<span class="nav-icon">✦</span><span>小幫手管理</span><b id="assistantPendingBadge" class="badge red hidden" style="margin-left:auto">0</b>';nav.insertBefore(btn,nav.querySelector('[data-page="logs"]'));btn.onclick=()=>{switchPage('assistant');a('topTitle').textContent='小幫手管理';loadAssistantAdmin()}}
 const content=document.querySelector('.content');
 if(content&&!a('page-assistant')){const page=document.createElement('section');page.id='page-assistant';page.className='page';page.innerHTML=`<div class="page-head"><div><h2>小幫手管理</h2><p>集中處理問題回報、回答規則與實際測試。</p></div><button class="btn primary" id="newAssistantRule">＋ 新增回答</button></div><div class="assistant-summary"><div><span>待處理回報</span><strong id="assistantPendingCount">0</strong></div><div><span>已建立回答</span><strong id="assistantRuleCount">0</strong></div><div><span>啟用中回答</span><strong id="assistantActiveCount">0</strong></div></div><div class="assistant-admin-tabs"><button class="assistant-admin-tab active" data-assistant-pane="reports">問題回報</button><button class="assistant-admin-tab" data-assistant-pane="rules">回答內容</button><button class="assistant-admin-tab" data-assistant-pane="test">測試小幫手</button></div><div id="assistant-pane-reports" class="assistant-admin-pane active"><div class="panel"><div id="assistantReportList"></div></div></div><div id="assistant-pane-rules" class="assistant-admin-pane"><div class="assistant-rule-layout"><div class="panel assistant-rule-list"><div id="assistantRuleList"></div></div><div class="editor-card"><h3 id="assistantRuleEditorTitle">新增回答</h3><input type="hidden" id="assistantRuleId"><div class="field"><label>關鍵字（逗號或換行分隔）</label><textarea id="assistantRuleKeywords" placeholder="例如：廣告架、招牌、燈箱"></textarea></div><div class="field"><label>回答內容</label><textarea id="assistantRuleReply"></textarea></div><div class="field"><label>推薦成員姓名（逗號或換行分隔）</label><textarea id="assistantRuleMembers" placeholder="姓名必須和成員資料一致"></textarea></div><div class="savebar"><label class="switch"><input id="assistantRuleActive" type="checkbox" checked>前台啟用</label><button class="btn danger hidden" id="deleteAssistantRule">刪除</button><button class="btn primary" id="saveAssistantRule">儲存回答</button></div></div></div></div><div id="assistant-pane-test" class="assistant-admin-pane"><div class="panel assistant-test-box"><h3>測試小幫手</h3><p class="muted">輸入問題，確認目前會使用哪一組回答及推薦哪些成員。</p><div class="assistant-test-form"><input id="assistantTestInput" placeholder="例如：老屋翻修怎麼開始？"><button class="btn primary" id="assistantTestBtn">開始測試</button></div><div id="assistantTestResult" class="assistant-test-result hidden"></div></div></div>`;content.appendChild(page);wire()}
}
function wire(){document.querySelectorAll('[data-assistant-pane]').forEach(b=>b.onclick=()=>showPane(b.dataset.assistantPane));a('newAssistantRule').onclick=()=>{showPane('rules');editRule(null)};a('saveAssistantRule').onclick=saveRule;a('deleteAssistantRule').onclick=deleteRule;a('assistantTestBtn').onclick=testRule;a('assistantTestInput').addEventListener('keydown',e=>{if(e.key==='Enter')testRule()});a('assistantReportList').addEventListener('click',handleReportClick);a('assistantRuleList').addEventListener('click',e=>{const row=e.target.closest('[data-rule-id]');if(row)editRule(assistantRules.find(x=>x.id===row.dataset.ruleId))})}
function showPane(name){document.querySelectorAll('.assistant-admin-tab').forEach(x=>x.classList.toggle('active',x.dataset.assistantPane===name));document.querySelectorAll('.assistant-admin-pane').forEach(x=>x.classList.toggle('active',x.id===`assistant-pane-${name}`))}
async function loadAssistantAdmin(){const [rr,rp]=await Promise.all([sb.from('bni_assistant_rules').select('*').order('sort_order'),sb.from('bni_assistant_reports').select('*').order('created_at',{ascending:false})]);if(rr.error||rp.error)return notice('小幫手資料讀取失敗。','error');assistantRules=rr.data||[];assistantReports=rp.data||[];renderAssistantAdmin()}
function renderAssistantAdmin(){const pending=assistantReports.filter(x=>x.status==='pending').length;a('assistantPendingCount').textContent=pending;a('assistantRuleCount').textContent=assistantRules.length;a('assistantActiveCount').textContent=assistantRules.filter(x=>x.is_active).length;const badge=a('assistantPendingBadge');badge.textContent=pending;badge.classList.toggle('hidden',!pending);a('assistantReportList').innerHTML=assistantReports.length?assistantReports.map(x=>`<div class="assistant-report-row"><div class="assistant-report-copy"><b>${esc(x.question)}</b><span class="assistant-status ${x.status}">${x.status==='pending'?'待處理':'已完成'}</span><span>${fmtTime(x.created_at)}</span></div><div class="assistant-row-actions">${x.status==='pending'?`<button class="btn secondary" data-report-answer="${x.id}">新增回答</button><button class="btn ghost" data-report-done="${x.id}">標記完成</button>`:`<button class="btn ghost" data-report-pending="${x.id}">重新開啟</button>`}</div></div>`).join(''):'<div class="empty">目前沒有問題回報。</div>';a('assistantRuleList').innerHTML=assistantRules.length?assistantRules.map(x=>`<div class="assistant-rule-row ${editingRule?.id===x.id?'active':''}" data-rule-id="${x.id}"><div class="assistant-rule-copy"><b>${esc((x.keywords||[]).slice(0,4).join('、')||'未設定關鍵字')}</b><span>${esc(x.reply||'')}</span></div><span class="badge ${x.is_active?'green':'red'}">${x.is_active?'啟用':'停用'}</span></div>`).join(''):'<div class="empty">目前沒有回答內容。</div>'}
function editRule(rule,question=''){editingRule=rule||null;a('assistantRuleEditorTitle').textContent=rule?'編輯回答':'新增回答';a('assistantRuleId').value=rule?.id||'';a('assistantRuleKeywords').value=rule?(rule.keywords||[]).join('、'):question;a('assistantRuleReply').value=rule?.reply||'';a('assistantRuleMembers').value=rule?(rule.member_names||[]).join('、'):'';a('assistantRuleActive').checked=rule?.is_active!==false;a('deleteAssistantRule').classList.toggle('hidden',!rule);renderAssistantAdmin()}
async function saveRule(){const keywords=splitList(a('assistantRuleKeywords').value),reply=a('assistantRuleReply').value.trim(),member_names=splitList(a('assistantRuleMembers').value);if(!keywords.length||!reply)return notice('請填寫關鍵字與回答內容。','error');const payload={keywords,reply,member_names,is_active:a('assistantRuleActive').checked,updated_at:new Date().toISOString()};const id=a('assistantRuleId').value;const res=id?await sb.from('bni_assistant_rules').update(payload).eq('id',id):await sb.from('bni_assistant_rules').insert({...payload,sort_order:(assistantRules.length+1)*10});if(res.error)return notice('回答儲存失敗：'+res.error.message,'error');notice('回答已儲存，前台小幫手會同步使用。');editRule(null);await loadAssistantAdmin()}
async function deleteRule(){const id=a('assistantRuleId').value;if(!id||!confirm('確定刪除這組回答？'))return;const {error}=await sb.from('bni_assistant_rules').delete().eq('id',id);if(error)return notice('刪除失敗：'+error.message,'error');editRule(null);await loadAssistantAdmin()}
async function handleReportClick(e){const answer=e.target.closest('[data-report-answer]'),done=e.target.closest('[data-report-done]'),pending=e.target.closest('[data-report-pending]');if(answer){const r=assistantReports.find(x=>x.id===answer.dataset.reportAnswer);showPane('rules');editRule(null,r?.question||'');return}const id=done?.dataset.reportDone||pending?.dataset.reportPending;if(!id)return;const status=done?'done':'pending';const {error}=await sb.from('bni_assistant_reports').update({status,resolved_at:status==='done'?new Date().toISOString():null}).eq('id',id);if(error)return notice('狀態更新失敗：'+error.message,'error');await loadAssistantAdmin()}
function normalize(s){return String(s||'').toLowerCase().replace(/[\s，,。！？!?、／/\-]/g,'')}
function findRule(q){const x=normalize(q);return assistantRules.filter(r=>r.is_active).map(rule=>({rule,score:Math.max(0,...(rule.keywords||[]).map(w=>{const k=normalize(w);return x.includes(k)?k.length:0}))})).filter(x=>x.score>0).sort((a,b)=>b.score-a.score)[0]?.rule||null}
function testRule(){const q=a('assistantTestInput').value.trim(),out=a('assistantTestResult');if(!q)return;const rule=findRule(q);out.classList.remove('hidden');out.innerHTML=rule?`<b>可以回答</b><div>${esc(rule.reply)}</div><div class="assistant-test-members">${(rule.member_names||[]).map(n=>`<span>${esc(n)}</span>`).join('')||'<span>未指定推薦成員</span>'}</div><p class="muted">命中關鍵字：${esc((rule.keywords||[]).filter(k=>normalize(q).includes(normalize(k))).join('、'))}</p>`:'<b style="color:var(--danger)">目前無法回答</b><div>這個問題目前沒有命中任何回答內容，可到「回答內容」新增關鍵字與回答。</div>'}
function arrangeEditorHeader(){const title=a('assistantRuleEditorTitle'),input=a('assistantRuleActive');if(!title||!input)return;const label=input.closest('label');label.lastChild.textContent='前台顯示';const head=document.createElement('div');head.className='assistant-editor-head';title.parentElement.insertBefore(head,title);head.append(title,label)}
install();arrangeEditorHeader();
})();
