(function(){
const LABELS={member_card_click:'人物查看',contact_click:'聯絡方式點擊',assistant_contact_click:'小幫手直接聯絡',chat_member_open:'小幫手推薦人物',chat_open:'開啟小幫手',chat_message:'使用者詢問',chat_intent:'選擇功能',chat_problem_pick:'選擇需求',need_select:'需求類別點擊',chat_fallback:'無法判斷',chat_unanswered_report:'問題回報'};
const CLICK_TYPES=new Set(['member_card_click','contact_click','assistant_contact_click','chat_member_open','chat_open','chat_intent','chat_problem_pick','need_select']);
let selectedFlow={type:'all',value:''};
const $f=id=>document.getElementById(id);
const escf=(v='')=>String(v).replace(/[&<>"']/g,s=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot',"'":'&#039;'}[s]));
function loadFlowCss(){if(document.querySelector('link[href^="./flow.css"]'))return;const l=document.createElement('link');l.rel='stylesheet';l.href='./flow.css?v=20260925-1';document.head.appendChild(l)}
function rangeRows(rows){const v=$f('flowRange')?.value||'30';if(v==='all')return rows;const days=Number(v)||30,cut=Date.now()-days*86400000;return rows.filter(x=>new Date(x.created_at).getTime()>=cut)}
function needName(x){return x.meta?.title||x.meta?.need_key||x.intent||'其他需求'}
function contactName(x){return x.meta?.label||x.meta?.type||'聯絡方式'}
function aggregate(rows,keyFn,limit=7){const m={};rows.forEach(x=>{const k=keyFn(x);if(k)m[k]=(m[k]||0)+1});return Object.entries(m).sort((a,b)=>b[1]-a[1]).slice(0,limit).map(([name,value])=>({name,value}))}
function renderNodeList(items,type){const max=Math.max(1,...items.map(x=>x.value));return items.length?items.map((x,i)=>`<button class="flow-node ${selectedFlow.type===type&&selectedFlow.value===x.name?'active':''}" data-flow-type="${type}" data-flow-value="${escf(x.name)}"><span class="flow-node-rank">${i+1}</span><span class="flow-node-copy"><b>${escf(x.name)}</b><small>${x.value} 次</small></span><span class="flow-node-meter"><i style="width:${Math.max(8,x.value/max*100)}%"></i></span></button>`).join(''):'<div class="flow-empty">尚無資料</div>'}
function installFlowUi(){loadFlowCss();const page=$f('page-logs');if(!page||$f('matchingFlow'))return;const oldToolbar=$f('logDetailToolbar');if(oldToolbar)oldToolbar.style.display='none';const oldPanel=page.querySelector('.detail-log-panel')||page.querySelector('.panel');if(oldPanel)oldPanel.style.display='none';const head=page.querySelector('.page-head');const select=head?.querySelector('select');if(select)select.closest('.field').style.display='none';const box=document.createElement('div');box.id='matchingFlow';box.innerHTML=`
<div class="flow-toolbar"><div><b>媒合流向</b><span>用流向看使用者從需求、人物到聯絡行為</span></div><select id="flowRange"><option value="7">近 7 天</option><option value="30" selected>近 30 天</option><option value="all">全部時間</option></select></div>
<div class="flow-summary" id="flowSummary"></div>
<div class="flow-map-card"><div class="flow-map-head"><div><h3>需求 → 人物 → 聯絡</h3><p>目前資料以彙總流向呈現；可點左右節點查看相關明細。</p></div><span class="flow-note">歷史資料尚未包含單一訪客識別，因此不把不同事件硬湊成同一人的完整路徑。</span></div>
<div class="flow-map"><div class="flow-column"><div class="flow-col-title">需求類別</div><div id="flowNeeds"></div></div><div class="flow-center"><div class="flow-hub"><span>人物媒合</span><strong id="flowPersonTotal">0</strong><small>次人物互動</small></div><div class="flow-lines left-lines"></div><div class="flow-lines right-lines"></div></div><div class="flow-column"><div class="flow-col-title">聯絡行為</div><div id="flowContacts"></div></div></div></div>
<div class="flow-people-card"><div class="flow-section-head"><div><h3>熱門人物節點</h3><p>圓越大代表互動越多；點人物可直接看明細。</p></div><button id="clearFlowFilter" class="flow-clear">清除篩選</button></div><div id="flowPeople" class="flow-people"></div></div>
<div class="flow-detail-card"><div class="flow-section-head"><div><h3 id="flowDetailTitle">詳細點擊統計</h3><p>不列時間，只統計每個人物、每一種按鈕的點擊數。</p></div><button id="toggleFlowDetail" class="flow-detail-toggle">展開統計</button></div><div id="flowDetail" class="flow-detail hidden"></div></div>`;head?.insertAdjacentElement('afterend',box);$f('flowRange').addEventListener('change',()=>renderFlow());$f('clearFlowFilter').onclick=()=>{selectedFlow={type:'all',value:''};renderFlow()};$f('toggleFlowDetail').onclick=()=>{$f('flowDetail').classList.toggle('hidden');$f('toggleFlowDetail').textContent=$f('flowDetail').classList.contains('hidden')?'展開統計':'收合統計'};box.addEventListener('click',e=>{const n=e.target.closest('[data-flow-type]');if(!n)return;selectedFlow={type:n.dataset.flowType,value:n.dataset.flowValue};renderFlow();$f('flowDetail').classList.remove('hidden');$f('toggleFlowDetail').textContent='收合統計'});
}
function filteredDetails(rows){if(selectedFlow.type==='need')return rows.filter(x=>(x.event_type==='need_select'||x.event_type==='chat_problem_pick')&&needName(x)===selectedFlow.value);if(selectedFlow.type==='member')return rows.filter(x=>x.member_name===selectedFlow.value);if(selectedFlow.type==='contact')return rows.filter(x=>(x.event_type==='contact_click'||x.event_type==='assistant_contact_click')&&contactName(x)===selectedFlow.value);return rows}
function renderPeople(rows){const people=aggregate(rows.filter(x=>x.member_name),x=>x.member_name,10),max=Math.max(1,...people.map(x=>x.value));$f('flowPeople').innerHTML=people.length?people.map((x,i)=>{const size=74+Math.round(x.value/max*54);return `<button class="person-bubble ${selectedFlow.type==='member'&&selectedFlow.value===x.name?'active':''}" data-flow-type="member" data-flow-value="${escf(x.name)}" style="width:${size}px;height:${size}px"><b>${escf(x.name)}</b><span>${x.value}</span></button>`}).join(''):'<div class="flow-empty">目前沒有足夠的人物互動資料。</div>'}
function actionName(x){if(x.event_type==='contact_click')return x.meta?.label?`聯絡｜${x.meta.label}`:'聯絡方式';if(x.event_type==='need_select'||x.event_type==='chat_problem_pick')return `需求｜${needName(x)}`;if(x.event_type==='chat_member_open')return '小幫手推薦人物';if(x.event_type==='chat_open')return '開啟小幫手';if(x.event_type==='chat_intent')return x.meta?.label?`功能｜${x.meta.label}`:'選擇功能';return LABELS[x.event_type]||x.event_type}
function actionClass(label){if(label==='人物查看')return 'view';if(label.startsWith('聯絡｜')||label==='聯絡方式')return 'contact';if(label.includes('小幫手'))return 'assistant';if(label.startsWith('需求｜')||label==='需求類別點擊'||label==='選擇需求')return 'need';if(label.startsWith('功能｜')||label==='選擇功能')return 'function';return 'other'}
function startOfDay(d){const x=new Date(d);x.setHours(0,0,0,0);return x}
function startOfWeek(d){const x=startOfDay(d),day=(x.getDay()+6)%7;x.setDate(x.getDate()-day);return x}
function startOfMonth(d){const x=startOfDay(d);x.setDate(1);return x}
function inRange(rows,start,end){return rows.filter(x=>{const t=new Date(x.created_at);return t>=start&&t<end})}
function pctChange(curr,prev){if(prev===0)return curr===0?0:null;return Math.round((curr-prev)/prev*100)}
function changeBadge(curr,prev){const p=pctChange(curr,prev);if(p===null)return `<span class="change-up">新增 ${curr}</span>`;if(p>0)return `<span class="change-up">↑ ${p}%</span>`;if(p<0)return `<span class="change-down">↓ ${Math.abs(p)}%</span>`;return '<span class="change-flat">— 0%</span>'}
function periodColumn(title,subtitle,rows,tone){const clicks=rows.filter(x=>CLICK_TYPES.has(x.event_type)),groups={};clicks.forEach(x=>{const person=x.member_name||((x.event_type==='need_select'||x.event_type==='chat_problem_pick')?'需求互動':'其他互動');groups[person]??={total:0,actions:{}};groups[person].total++;const a=actionName(x);groups[person].actions[a]=(groups[person].actions[a]||0)+1});const people=Object.entries(groups).sort((a,b)=>b[1].total-a[1].total);return `<section class="period-col period-${tone}"><div class="period-head"><div><b>${escf(title)}</b><span>${escf(subtitle)}</span></div><strong>${clicks.length}</strong></div><div class="period-body">${people.length?people.map(([person,data])=>`<div class="period-person"><div class="period-person-head"><b>${escf(person)}</b><span>${data.total}</span></div><div class="period-actions">${Object.entries(data.actions).sort((a,b)=>b[1]-a[1]).map(([label,count])=>`<div class="period-action action-${actionClass(label)}"><span><i></i>${escf(label)}</span><strong>${count}</strong></div>`).join('')}</div></div>`).join(''):'<div class="flow-empty">尚無點擊資料</div>'}</div></section>`}
function renderDetail(rows){const base=filteredDetails(rows),now=new Date(),todayStart=startOfDay(now),tomorrow=new Date(todayStart);tomorrow.setDate(tomorrow.getDate()+1);const yesterday=new Date(todayStart);yesterday.setDate(yesterday.getDate()-1);const weekStart=startOfWeek(now),nextWeek=new Date(weekStart);nextWeek.setDate(nextWeek.getDate()+7);const prevWeekStart=new Date(weekStart);prevWeekStart.setDate(prevWeekStart.getDate()-7);const monthStart=startOfMonth(now),nextMonth=new Date(monthStart);nextMonth.setMonth(nextMonth.getMonth()+1);const prevMonthStart=new Date(monthStart);prevMonthStart.setMonth(prevMonthStart.getMonth()-1);const monthRows=inRange(base,monthStart,nextMonth),weekRows=inRange(base,weekStart,nextWeek),dayRows=inRange(base,todayStart,tomorrow),prevMonthRows=inRange(base,prevMonthStart,monthStart),prevWeekRows=inRange(base,prevWeekStart,weekStart),prevDayRows=inRange(base,yesterday,todayStart);const clickCount=r=>r.filter(x=>CLICK_TYPES.has(x.event_type)).length;const mc=clickCount(monthRows),wc=clickCount(weekRows),dc=clickCount(dayRows),pm=clickCount(prevMonthRows),pw=clickCount(prevWeekRows),pd=clickCount(prevDayRows);const mm=String(now.getMonth()+1).padStart(2,'0'),dd=String(now.getDate()).padStart(2,'0');$f('flowDetailTitle').textContent=selectedFlow.type==='all'?'詳細點擊統計':`${selectedFlow.value}｜點擊統計`;$f('flowDetail').innerHTML=`<div class="period-changes"><div><span>本月變化</span><strong>${mc} 次</strong>${changeBadge(mc,pm)}<small>與上月相比</small></div><div><span>本週變化</span><strong>${wc} 次</strong>${changeBadge(wc,pw)}<small>與上週相比</small></div><div><span>今日變化</span><strong>${dc} 次</strong>${changeBadge(dc,pd)}<small>與昨日相比</small></div></div><div class="period-grid">${periodColumn('本月統計',`${mm} 月`,monthRows,'month')}${periodColumn('本週統計','本週',weekRows,'week')}${periodColumn('今日紀錄',`${mm}/${dd}`,dayRows,'today')}</div>`}
function renderFlow(){installFlowUi();if(!$f('matchingFlow'))return;const rows=rangeRows(events||[]),needRows=rows.filter(x=>x.event_type==='need_select'||x.event_type==='chat_problem_pick'),personRows=rows.filter(x=>x.event_type==='member_card_click'||x.event_type==='chat_member_open'),contactRows=rows.filter(x=>x.event_type==='contact_click'||x.event_type==='assistant_contact_click'),needs=aggregate(needRows,needName,7),contacts=aggregate(contactRows,contactName,7),people=aggregate(personRows,x=>x.member_name||'未標記人物',50);const conv=personRows.length?Math.round(contactRows.length/personRows.length*100):0;$f('flowSummary').innerHTML=`<div><span>需求選擇</span><strong>${needRows.length}</strong></div><div><span>人物互動</span><strong>${personRows.length}</strong></div><div><span>聯絡點擊</span><strong>${contactRows.length}</strong></div><div><span>查看→聯絡</span><strong>${conv}%</strong></div>`;$f('flowNeeds').innerHTML=renderNodeList(needs,'need');$f('flowContacts').innerHTML=renderNodeList(contacts,'contact');$f('flowPersonTotal').textContent=personRows.length;renderPeople(rows);renderDetail(events||[])}
window.loadLogs=async function(){installFlowUi();const {data,error}=await sb.from('bni_behavior_events').select('*').order('created_at',{ascending:false}).limit(3000);if(error)return notice('媒合紀錄讀取失敗：'+error.message,'error');events=data||[];renderFlow()};
window.renderLogs=function(){renderFlow()};
installFlowUi();
})();
