(function(){
const LABELS={member_card_click:'人物查看',contact_click:'聯絡方式點擊',chat_member_open:'小幫手推薦人物',chat_open:'開啟小幫手',chat_message:'使用者詢問',chat_intent:'選擇功能',chat_problem_pick:'選擇需求',need_select:'需求類別點擊',chat_fallback:'無法判斷'};
let selectedFlow={type:'all',value:''};
const $f=id=>document.getElementById(id);
const escf=(v='')=>String(v).replace(/[&<>"']/g,s=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[s]));
function loadFlowCss(){if(document.querySelector('link[href="./flow.css"]'))return;const l=document.createElement('link');l.rel='stylesheet';l.href='./flow.css';document.head.appendChild(l)}
function rangeRows(rows){const v=$f('flowRange')?.value||'30';if(v==='all')return rows;const days=Number(v)||30,cut=Date.now()-days*86400000;return rows.filter(x=>new Date(x.created_at).getTime()>=cut)}
function needName(x){return x.meta?.title||x.meta?.need_key||x.intent||'其他需求'}
function contactName(x){return x.meta?.label||x.meta?.type||'聯絡方式'}
function aggregate(rows,keyFn,limit=7){const m={};rows.forEach(x=>{const k=keyFn(x);if(k)m[k]=(m[k]||0)+1});return Object.entries(m).sort((a,b)=>b[1]-a[1]).slice(0,limit).map(([name,value])=>({name,value}))}
function renderNodeList(items,type){const max=Math.max(1,...items.map(x=>x.value));return items.length?items.map((x,i)=>`<button class="flow-node ${selectedFlow.type===type&&selectedFlow.value===x.name?'active':''}" data-flow-type="${type}" data-flow-value="${escf(x.name)}"><span class="flow-node-rank">${i+1}</span><span class="flow-node-copy"><b>${escf(x.name)}</b><small>${x.value} 次</small></span><span class="flow-node-meter"><i style="width:${Math.max(8,x.value/max*100)}%"></i></span></button>`).join(''):'<div class="flow-empty">尚無資料</div>'}
function installFlowUi(){loadFlowCss();const page=$f('page-logs');if(!page||$f('matchingFlow'))return;const oldToolbar=$f('logDetailToolbar');if(oldToolbar)oldToolbar.style.display='none';const oldPanel=page.querySelector('.detail-log-panel')||page.querySelector('.panel');if(oldPanel)oldPanel.style.display='none';const head=page.querySelector('.page-head');const select=head?.querySelector('select');if(select)select.closest('.field').style.display='none';const box=document.createElement('div');box.id='matchingFlow';box.innerHTML=`
<div class="flow-toolbar"><div><b>媒合流向</b><span>用流向看使用者從需求、人物到聯絡行為</span></div><select id="flowRange"><option value="7">近 7 天</option><option value="30" selected>近 30 天</option><option value="all">全部時間</option></select></div>
<div class="flow-summary" id="flowSummary"></div>
<div class="flow-map-card"><div class="flow-map-head"><div><h3>需求 → 人物 → 聯絡</h3><p>目前資料以彙總流向呈現；可點左右節點查看相關明細。</p></div><span class="flow-note">歷史資料尚未包含單一訪客識別，因此不把不同事件硬湊成同一人的完整路徑。</span></div>
<div class="flow-map"><div class="flow-column"><div class="flow-col-title">需求類別</div><div id="flowNeeds"></div></div><div class="flow-center"><div class="flow-hub"><span>人物媒合</span><strong id="flowPersonTotal">0</strong><small>次人物互動</small></div><div class="flow-lines left-lines"></div><div class="flow-lines right-lines"></div></div><div class="flow-column"><div class="flow-col-title">聯絡行為</div><div id="flowContacts"></div></div></div></div>
<div class="flow-people-card"><div class="flow-section-head"><div><h3>熱門人物節點</h3><p>圓越大代表互動越多；點人物可直接看明細。</p></div><button id="clearFlowFilter" class="flow-clear">清除篩選</button></div><div id="flowPeople" class="flow-people"></div></div>
<div class="flow-detail-card"><div class="flow-section-head"><div><h3 id="flowDetailTitle">詳細紀錄</h3><p>展開後會按「日期 → 人物」整理，快速看每個人在當天被點擊了什麼。</p></div><button id="toggleFlowDetail" class="flow-detail-toggle">展開明細</button></div><div id="flowDetail" class="flow-detail hidden"></div></div>`;head?.insertAdjacentElement('afterend',box);$f('flowRange').addEventListener('change',()=>renderFlow());$f('clearFlowFilter').onclick=()=>{selectedFlow={type:'all',value:''};renderFlow()};$f('toggleFlowDetail').onclick=()=>{$f('flowDetail').classList.toggle('hidden');$f('toggleFlowDetail').textContent=$f('flowDetail').classList.contains('hidden')?'展開明細':'收合明細'};box.addEventListener('click',e=>{const n=e.target.closest('[data-flow-type]');if(!n)return;selectedFlow={type:n.dataset.flowType,value:n.dataset.flowValue};renderFlow();$f('flowDetail').classList.remove('hidden');$f('toggleFlowDetail').textContent='收合明細'});
}
function filteredDetails(rows){if(selectedFlow.type==='need')return rows.filter(x=>(x.event_type==='need_select'||x.event_type==='chat_problem_pick')&&needName(x)===selectedFlow.value);if(selectedFlow.type==='member')return rows.filter(x=>x.member_name===selectedFlow.value);if(selectedFlow.type==='contact')return rows.filter(x=>x.event_type==='contact_click'&&contactName(x)===selectedFlow.value);return rows}
function renderPeople(rows){const people=aggregate(rows.filter(x=>x.member_name),x=>x.member_name,10),max=Math.max(1,...people.map(x=>x.value));$f('flowPeople').innerHTML=people.length?people.map((x,i)=>{const size=74+Math.round(x.value/max*54);return `<button class="person-bubble ${selectedFlow.type==='member'&&selectedFlow.value===x.name?'active':''}" data-flow-type="member" data-flow-value="${escf(x.name)}" style="width:${size}px;height:${size}px"><b>${escf(x.name)}</b><span>${x.value}</span></button>`}).join(''):'<div class="flow-empty">目前沒有足夠的人物互動資料。</div>'}
function detailText(x){if(x.event_type==='contact_click')return x.meta?.label||x.meta?.type||'聯絡方式';if(x.event_type==='need_select'||x.event_type==='chat_problem_pick')return needName(x);if(x.event_type==='chat_message')return x.query_text||'詢問內容';return x.query_text||x.meta?.label||x.meta?.title||''}
function renderDetail(rows){const rr=filteredDetails(rows).slice(0,160);const title=selectedFlow.type==='all'?'全部詳細紀錄':`${selectedFlow.value}｜相關紀錄`;$f('flowDetailTitle').textContent=title;if(!rr.length){$f('flowDetail').innerHTML='<div class="flow-empty">沒有符合的紀錄。</div>';return}const dateGroups={};rr.forEach(x=>{const d=new Intl.DateTimeFormat('zh-TW',{timeZone:'Asia/Taipei',month:'2-digit',day:'2-digit'}).format(new Date(x.created_at));const person=x.member_name||((x.event_type==='need_select'||x.event_type==='chat_problem_pick')?'需求互動':'其他互動');dateGroups[d]??={};dateGroups[d][person]??=[];dateGroups[d][person].push(x)});$f('flowDetail').innerHTML=`<div class="flow-detail-grid">${Object.entries(dateGroups).map(([d,people])=>{const total=Object.values(people).reduce((n,a)=>n+a.length,0);return `<section class="flow-date-col"><div class="flow-date-head"><div><b>${escf(d)}</b><span>${Object.keys(people).length} 人／${total} 次互動</span></div></div><div class="flow-date-people">${Object.entries(people).map(([person,items])=>`<div class="flow-person-block"><div class="flow-person-head"><b>${escf(person)}</b><span>${items.length}</span></div><div class="flow-person-actions">${items.map(x=>`<div class="flow-action"><time>${fmtTime(x.created_at)}</time><span>${escf(LABELS[x.event_type]||x.event_type)}</span>${detailText(x)?`<small>${escf(detailText(x))}</small>`:''}</div>`).join('')}</div></div>`).join('')}</div></section>`}).join('')}</div>`}
function renderFlow(){installFlowUi();if(!$f('matchingFlow'))return;const rows=rangeRows(events||[]),needRows=rows.filter(x=>x.event_type==='need_select'||x.event_type==='chat_problem_pick'),personRows=rows.filter(x=>x.event_type==='member_card_click'||x.event_type==='chat_member_open'),contactRows=rows.filter(x=>x.event_type==='contact_click'),needs=aggregate(needRows,needName,7),contacts=aggregate(contactRows,contactName,7),people=aggregate(personRows,x=>x.member_name||'未標記人物',50);const conv=personRows.length?Math.round(contactRows.length/personRows.length*100):0;$f('flowSummary').innerHTML=`<div><span>需求選擇</span><strong>${needRows.length}</strong></div><div><span>人物互動</span><strong>${personRows.length}</strong></div><div><span>聯絡點擊</span><strong>${contactRows.length}</strong></div><div><span>查看→聯絡</span><strong>${conv}%</strong></div>`;$f('flowNeeds').innerHTML=renderNodeList(needs,'need');$f('flowContacts').innerHTML=renderNodeList(contacts,'contact');$f('flowPersonTotal').textContent=personRows.length;renderPeople(rows);renderDetail(rows);const topP=people[0];if(topP&&selectedFlow.type==='all')$f('flowDetailTitle').textContent=`詳細紀錄｜目前互動最高：${topP.name}`}
window.loadLogs=async function(){installFlowUi();const {data,error}=await sb.from('bni_behavior_events').select('*').order('created_at',{ascending:false}).limit(1500);if(error)return notice('媒合紀錄讀取失敗：'+error.message,'error');events=data||[];renderFlow()};
window.renderLogs=function(){renderFlow()};
installFlowUi();
})();