(function(){
const qs=id=>document.getElementById(id);
let stepMap={};
let loadedKey=null;
let dragMemberId=null;
function esc2(v=''){return String(v).replace(/[&<>"']/g,s=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[s]))}
function ensureCss(){if(document.querySelector('link[href^="./matching-steps.css"]'))return;const l=document.createElement('link');l.rel='stylesheet';l.href='./matching-steps.css?v=20260915-1610';document.head.appendChild(l)}
function stepNames(){return (qs('cat_steps')?.value||'').split('\n').map(x=>x.trim()).filter(Boolean)}
function memberById(id){return members.find(m=>m.id===id)}
function sourceCards(){return members.map(m=>`<div class="drag-member" draggable="true" data-drag-member="${m.id}"><b>${m.member_no||'-'}｜${esc2(m.name)}</b><span>${esc2(m.company||'')}</span></div>`).join('')}
function assignedCards(i){const ids=stepMap[i]||[];return ids.map(id=>{const m=memberById(id);if(!m)return'';return `<div class="assigned-member"><span><b>${m.member_no||'-'}｜${esc2(m.name)}</b><small>${esc2(m.company||'')}</small></span><button type="button" data-remove-step="${i}" data-remove-member="${id}">×</button></div>`}).join('')}
function arrangeCategoryEditor(){const editor=qs('categoryEditor');if(!editor)return;
 const active=qs('cat_active')?.closest('.switch');if(active){let top=qs('categoryActiveTop');if(!top){top=document.createElement('div');top.id='categoryActiveTop';top.className='category-active-top';top.innerHTML='<div><b>前台顯示類別</b><span>關閉後，此問題類別不會顯示在前台。</span></div>';editor.insertBefore(top,editor.firstChild)}if(!top.contains(active))top.appendChild(active)}
 const desc=qs('cat_description')?.closest('.field'),steps=qs('cat_steps')?.closest('.field');if(desc&&steps&&!desc.parentElement.classList.contains('category-copy-grid')){const grid=document.createElement('div');grid.className='category-copy-grid';desc.parentNode.insertBefore(grid,desc);grid.appendChild(desc);grid.appendChild(steps)}
 const sortField=qs('cat_sort')?.closest('.field');if(sortField)sortField.style.display='none';const preview=qs('categoryOrderPreview');if(preview)preview.remove();
}
function renderStepUi(){const box=qs('categoryMemberPicks');if(!box||!currentCategory)return;const h=box.previousElementSibling?.previousElementSibling;if(h&&h.tagName==='H3')h.textContent='步驟配對';const p=box.previousElementSibling;if(p)p.textContent='先確認步驟，再把左側成員拖到對應步驟。同一個人可以放在多個步驟。';const steps=stepNames();box.innerHTML=`<div class="step-match-layout"><aside class="step-member-source"><div class="step-source-head"><b>可配對成員</b><span>拖曳到右側步驟</span></div><input id="stepMemberSearch" placeholder="搜尋姓名、公司…"><div id="stepMemberSourceList">${sourceCards()}</div></aside><div class="step-zones">${steps.length?steps.map((s,i)=>`<section class="step-zone" data-drop-step="${i}"><div class="step-zone-head"><span class="step-no">Step ${i+1}</span><b>${esc2(s)}</b><span>${(stepMap[i]||[]).length} 人</span></div><div class="step-zone-body">${assignedCards(i)||'<div class="drop-hint">拖曳成員到這裡</div>'}</div></section>`).join(''):'<div class="step-empty">請先在上方輸入處理步驟，每行一個步驟。</div>'}</div></div>`;
 bindDrag();
 const search=qs('stepMemberSearch');if(search)search.oninput=()=>{const q=search.value.trim().toLowerCase();document.querySelectorAll('.drag-member').forEach(el=>{el.style.display=el.textContent.toLowerCase().includes(q)?'grid':'none'})};
 box.querySelectorAll('[data-remove-step]').forEach(btn=>btn.onclick=()=>{const i=Number(btn.dataset.removeStep),id=btn.dataset.removeMember;stepMap[i]=(stepMap[i]||[]).filter(x=>x!==id);renderStepUi()});
}
function bindDrag(){document.querySelectorAll('[data-drag-member]').forEach(el=>{el.ondragstart=e=>{dragMemberId=el.dataset.dragMember;e.dataTransfer.effectAllowed='copy';el.classList.add('dragging')};el.ondragend=()=>{dragMemberId=null;el.classList.remove('dragging')}});document.querySelectorAll('[data-drop-step]').forEach(zone=>{zone.ondragover=e=>{e.preventDefault();zone.classList.add('drag-over')};zone.ondragleave=()=>zone.classList.remove('drag-over');zone.ondrop=e=>{e.preventDefault();zone.classList.remove('drag-over');if(!dragMemberId)return;const i=Number(zone.dataset.dropStep);stepMap[i]??=[];if(!stepMap[i].includes(dragMemberId))stepMap[i].push(dragMemberId);renderStepUi()}})}
async function loadStepMap(){if(!currentCategory?.key){stepMap={};loadedKey='';renderStepUi();return}const key=currentCategory.key;if(loadedKey===key)return;loadedKey=key;const {data,error}=await sb.from('bni_need_step_members').select('*').eq('need_key',key).order('step_index').order('sort_order');if(error){console.warn('步驟配對讀取失敗',error);stepMap={};renderStepUi();return}stepMap={};(data||[]).forEach(r=>{stepMap[r.step_index]??=[];stepMap[r.step_index].push(r.member_id)});renderStepUi()}
async function saveAll(){let key=val('cat_key').toLowerCase().replace(/\s+/g,'_').replace(/[^a-z0-9_\-]/g,'');if(!key)return notice('類別代碼請使用英文或數字。','error');const title=val('cat_title');if(!title)return notice('請輸入類別名稱。','error');const steps=stepNames();const existingSort=Number(val('cat_sort'))||Number(currentCategory?.sort_order)||categories.length+1;const p={key,icon:val('cat_icon')||'•',title,small:val('cat_small')||null,description:val('cat_description')||null,steps,sort_order:existingSort,is_active:qs('cat_active').checked,updated_at:new Date().toISOString()};let result;if(currentCategory?.key){const {key:_,...u}=p;result=await sb.from('bni_need_categories').update(u).eq('key',currentCategory.key)}else result=await sb.from('bni_need_categories').insert(p);if(result.error)return notice('類別儲存失敗：'+result.error.message,'error');const targetKey=currentCategory?.key||key;
 const del1=await sb.from('bni_need_step_members').delete().eq('need_key',targetKey);if(del1.error)return notice('步驟配對更新失敗：'+del1.error.message,'error');
 const stepRows=[];Object.entries(stepMap).forEach(([idx,ids])=>ids.forEach((id,n)=>stepRows.push({need_key:targetKey,step_index:Number(idx),member_id:id,sort_order:n+1})));if(stepRows.length){const ins=await sb.from('bni_need_step_members').insert(stepRows);if(ins.error)return notice('步驟配對儲存失敗：'+ins.error.message,'error')}
 const uniqueIds=[...new Set(stepRows.map(x=>x.member_id))];const del2=await sb.from('bni_need_members').delete().eq('need_key',targetKey);if(del2.error)return notice('人物配對更新失敗：'+del2.error.message,'error');if(uniqueIds.length){const rows=uniqueIds.map((id,i)=>({need_key:targetKey,member_id:id,sort_order:i+1}));const ins2=await sb.from('bni_need_members').insert(rows);if(ins2.error)return notice('人物配對儲存失敗：'+ins2.error.message,'error')}
 notice('類別、步驟與人物配對已同步到前台。');loadedKey=null;await loadCategories();selectCategory(targetKey);setTimeout(()=>{arrangeCategoryEditor();loadStepMap()},0)
}
function wire(){ensureCss();arrangeCategoryEditor();const editor=qs('categoryEditor'),box=qs('categoryMemberPicks'),save=qs('saveCategoryBtn'),steps=qs('cat_steps');if(!editor||!box||!save||!steps)return;save.onclick=saveAll;if(!steps.dataset.stepWire){steps.dataset.stepWire='1';steps.addEventListener('input',()=>{const names=stepNames();Object.keys(stepMap).forEach(k=>{if(Number(k)>=names.length)delete stepMap[k]});renderStepUi()})}if(!editor.classList.contains('hidden'))loadStepMap()}
document.addEventListener('click',e=>{if(e.target.closest('[data-category]')||e.target.closest('#addCategoryBtn'))setTimeout(()=>{loadedKey=null;wire()},0)});
wire();
})();